### ISSUE TITLE
Default Source Location

### ISSUE THREAD

**Issue by curvatura99** [PRATAP-KUMAR/ubuntu-gdm-set-background#1]
The default source location is here:
source="/usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource"

However I use the Gnome login background since I don't like the purple and orange accents. I changed the source as follows:
source="/usr/share/gnome-shell/gnome-shell-theme.gresource"

Now it changes the background using the default Gnome login background. Maybe a check to see which login screen is being used would be helpful?

**Comment by PRATAP-KUMAR** [comment]
Hi, thats a nice point from you.
Will workout about this by tomorrow n update the script.
Thank You.

**Comment by SylChamber** [comment]
I have a similar problem under Pop!_OS 22.04, where the theme is `Pop`, in the same folder as `Yaru`, but no `Yaru` to be found.

To me, the way to find the current theme seems to use `/usr/share/gnome-shell/gdm-theme.gresource` as source, because it's a symbolic link to `/etc/alternatives/gdm-theme.gresource`, which is _another_ link that points to the _current_ theme. I would pick the link under `/usr/share/gnome-shell` rather than the one under `/etc` because it's closer to the theme.

I also would add some path tests before proceeding because the script throws errors.

I may produce a pull request.

**Comment by PRATAP-KUMAR** [comment]
@curvatura99 sorry for the very late reply, almost 1 and half year.
I made a work around for this in the recent version of Ubuntu which is 23.04.

Can you try with the script `ubuntu-gdm-set-background-23.04-transparent`

**Comment by PRATAP-KUMAR** [comment]
@curvatura99 Hi, did you get a chance to upgrade to 23.04?

**Comment by PRATAP-KUMAR** [comment]
For Ubuntu 20.04, now you can choose the source between `yaru || vanilla`.
